services:
  montago-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: montago
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  montago-api:
    build:
      context: ./backend/MontagGo.API
      dockerfile: Dockerfile  # für Production
    depends_on:
      - montago-db
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=montago-db;Database=montago;Username=postgres;Password=postgres

volumes:
  postgres-data:
